spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#    format:
#      date: iso
      ##convert for @Controller

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
    ##enabled open transaction in controller layer

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8091

bot.name: xmr_bingo_bot
bot.key: 7438604237:AAH-rHbOYV5xQ1eamxwSKa9XdUuRM_hysAs